# Generated by Django 5.0.6 on 2024-06-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cards_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='car',
        ),
        migrations.AddField(
            model_name='cars',
            name='rfids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='home.cards'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='rfid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
