# Generated by Django 4.2.13 on 2024-06-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_cards_car_cars_rfids_alter_cards_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='firmware_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
