# Generated by Django 4.2.13 on 2024-06-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_firmware_firmware_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='rfid',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
